### PR TITLE
Issue 456 - Added Opening Book Icon to pairing pages, links on profiles and Updated accessibility 

### PR DESCRIPTION
**Pull request by MattMaginniss**
For issue https://github.com/Lichess4545/heltour/issues/456:

What did I do?
- Created opening book SVG icon
- Added opening book icon to 4545 and lone pairings (includes blitz battle and 960)
- Updated the alignment of download games icon and opening book icons.
- Added alt text to download games and opening book icons for accessibility
- Added Download games and Opening book links to profile page

Current 4545 Desktop:
immagine

Updated 4545 Desktop:
immagine

Current 4545 Mobile:
immagine

Updated 4545 Mobile:
immagine

Current Lonewolf:
immagine

Updated Lonewolf:
immagine

Current Profile:
immagine

Updated Profile: 
immagine

### CODE REVIEW

**Review by lakinwecker — APPROVED** [review]
LGTM

**Comment by lakinwecker** [comment]
Thanks for the contribution!

**Comment by psoumitri** [comment]
This is great Matt, thanks very much. Just seen it on the website! One minor enhancement would be to actually get the explorer colors right in the 4545 Pairings page. Just using the color as the suffix to the link seems to do it  .. e.g. "/white" or "/black" - seems to default to "/white" if missing.

**Comment by lakinwecker** [comment]
@psoumitri open a new github issue for this and we can try and make it happen.

**Pull request merged**
